id: P000273
initial_creation_type: ebook
source_metadata:
  title: ᨏ ཞལ་གདམས་གསལ་བའི་སྒྲོན་མ་བཞུགས་སོ༔
  authors:
  - མཛད་པ་པོ། རཏྣ་གླིང་པ།
  layers:
  - book_title
  - author
  id: SHE-RTD-020
web_metadata:
  title:
    en: The Illuminating Lamp of Advice
    bo: ཞལ་གདམས་གསལ་བའི་སྒྲོན་མ་བཞུགས་སོ༔
  collection:
    en: Treasury of Precious Termas–  Book 20
    bo: ''
  author:
    en: Ratna Lingpa
    bo: ''
  pusblisher:
    en: Shechen Publications
    bo: ''
  sku: SHE-RTD-020
  category:
    en: Uncategorized
    bo: སྡེ་ཚན་མེད་པ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-RTD-020.epub
  description:
    en: ''
    bo: ''
